version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=swagger"
      - "POSTGRES_PASSWORD=swagger"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - .:/swagger_api
    ports:
      - "3000:3000"
    depends_on:
      - db
  web_api:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      # Nginxの設定ファイル 一応CORS用に作成
      - ./swagger/swagger-editor.conf:/etc/nginx/conf.d/default.conf:ro
      - ./swagger/api.yaml:/usr/share/nginx/html/api.yaml:ro
      - ./swagger/swagger-ui:/usr/share/nginx/html/swagger-ui:ro
    links:
      - swagger_editor:swagger_editor
    depends_on:
      - swagger_editor
  swagger_editor:
    image: swaggerapi/swagger-editor:latest
