swagger: "2.0"
info:
  description: "Rails環境におけるAPIドキュメント管理"
  version: "1.0.0"
  title: "Swagger"
host: "127.0.0.1:3000"
schemes:
- "https"
- "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /:
    get:
      tags:
        - "トップ"
      summary: "Top"
      operationId: "getUser"
      responses:
        200:
          description: "top#index"
          schema:
            $ref: "#/definitions/Response_Top"
  /users:
    get:
      tags:
        - "ユーザー一覧"
      summary: "Response all user"
      description: "全てのユーザー一覧を取得する"
      operationId: "getAllUser"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/User"
    post:
      tags:
        - "ユーザー作成"
      summary: "Create user"
      description: "ユーザーを作成する"
      operationId: "createUser"
      parameters:
        - name: "name"
          in: "query"
          required: "true"
          type: "string"
        - name: "age"
          in: "query"
          required: "true"
          type: "integer"
        - name: "birthday"
          in: "query"
          required: "true"
          type: "string"
        - name: "email"
          in: "query"
          required: "true"
          type: "string"
      responses:
        201:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/User"
        400:
          description: "bad request"
definitions:
  Response_Top:
    type: "object"
    properties:
      data:
        type: "string"
        example: "LT会議 ライトニングトーク"
  User:
    required: ["name", "age", "birthday", "email"]
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        example: "レバ太郎"
      age:
        type: "integer"
        example: "20"
      birthday:
        type: "string"
        example: "2010-01-01"
      email:
        type: "string"
        example: "levetaro@leve.jp"
