swagger: "2.0"
info:
  description: |
    Rails環境におけるAPIドキュメント管理
  version: "1.0.0"
  title: "Swagger"
# hostの重複は不可
# host: "swagger-api-sample-p.herokuapp.com"
host: "127.0.0.1:3000"
schemes:
- "http"
- "https"
paths:
  /:
    get:
      tags:
        - トップ
      summary: Top
      response:
        200:
          description: top#index
          schema:
            type: string
            example: LT会議 ライトニングトーク
  /users:
    get:
      tags:
        - ユーザー一覧
      summary: Response all user
      description: 全てのユーザー一覧を取得する
      operationId: "findPetsByStatus"
      produces:
        - "application/json"
      responses:
        200:
          description: successful operation
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        name:
          type: string
          example: レバ太郎
        age:
          type: integer
          format: int32
          example: 20
        birthday:
          type: string
          format: datetime
          example: "2010-01-01"
        email:
          type: string
          example: levetaro@leve.jp
