swagger: "2.0"
info:
  description: "Rails環境におけるAPIドキュメント管理"
  version: "1.0.0"
  title: "Swagger"
host: "127.0.0.1:3000"
schemes:
- "https"
- "http"
paths:
  /:
    get:
      tags:
        - "トップ"
      summary: "Top"
      operationId: "getUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "top#index"
          schema:
            $ref: "#/definitions/Response_Top"
  /users:
    get:
      tags:
        - "ユーザー一覧"
      summary: "Response all user"
      description: "全てのユーザー一覧を取得する"
      operationId: "getAllUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
    post:
      tags:
        - "ユーザー作成"
      summary: "Create user"
      description: "ユーザーを作成する"
      operationId: "createUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/UserParams"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
definitions:
  Response_Top:
    type: "object"
    properties:
      status:
        type: "integer"
        example: "200"
      data:
        type: "string"
        example: "LT会議 ライトニングトーク"
  User:
    type: "object"
    properties:
      user:
        $ref: "#/definitions/User"
  UserParams:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        example: "レバ太郎"
      age:
        type: "integer"
        example: "20"
      birthday:
        type: "string"
        example: "2010-01-01"
      email:
        type: "string"
        example: "levetaro@leve.jp"
